### ISSUE TITLE
AttributeError: 'HiveServer2Cursor' object has no attribute 'lastrowid'

### ISSUE THREAD

**Issue by cathmonster** [cloudera/impyla#141]
Hi,

What are implications of getting inserts working for pandas df with error above, code is bellow:
engine = sqlalchemy.engine.create_engine('impala://' + ihost)

metadata = MetaData(bind=engine)

mytable = Table("mytable", metadata,
      Column('mytable_id', sqlalchemy.INT),
      Column('col1', STRING),
      Column('col2', STRING),
      Column('col3', STRING),
)
mytable.drop()
mytable.create(engine)
##print CreateTable(mytable)
TESTDATA=StringIO(u"""mytable_id;col1;col2;col3
1;'anotherText';'sometext';'moretext'
""")

df = pd.DataFrame.from_csv(TESTDATA, sep=";")
print(df.head(10))

df.to_sql(name="mytable", con=engine,  index=False, if_exists='replace', flavor="mysql",
          dtype={'col1': String,'col2': String,'col3': String})

Should I just catch error and keep going ...

**Comment by laserson** [comment]
Is it necessary for you to be able to use the exact same code for working with Impala and other databases?  Either way, check out Ibis, as it may already have built in the ability to support multiple databases.

**Comment by el-stano** [comment]
Hi, 

I had the same issue when trying to use `impyla` with `SQLAlchemy`.

```
>>> session.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1213, in _execute_context
    result = context._setup_crud_result_proxy()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 1029, in _setup_crud_result_proxy
    self._setup_ins_pk_from_lastrowid()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 1065, in _setup_ins_pk_from_lastrowid
    lastrowid = self.get_lastrowid()
  File "/home/debian/projects/my_project/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 1001, in get_lastrowid
    return self.cursor.lastrowid
AttributeError: 'HiveServer2Cursor' object has no attribute 'lastrowid'
```

**Comment by el-stano** [comment]
Here is my attempt to fix this https://github.com/cloudera/impyla/pull/308.
