### ISSUE TITLE
Operational Error - "Operation is in ERROR_STATE"

### ISSUE THREAD

**Issue by gittify** [cloudera/impyla#200]
How do I get the error details along with this error?

**Comment by wesm** [comment]
This should be easy to add (we are retrieving the error message, but discarding it). Can you produce an example query that yields ERROR_STATE?

**Comment by gittify** [comment]
If we try to insert into  a table that is created as follows:

INSERT query - insert into test_table partition (dt,installtime) values ('key1','nos','type1','2016-06-08 00:00:00', '2016-08-04 01:01:01');

CREATE  TABLE test_table(
      id string,
      name string,
      type string)
     PARTITIONED BY ( 
       dt string,
       installtime string)
     ROW FORMAT DELIMITED 
       FIELDS TERMINATED BY '\001' 
     STORED AS INPUTFORMAT 
       'org.apache.hadoop.hive.ql.io.RCFileInputFormat' 
     OUTPUTFORMAT 
       'org.apache.hadoop.hive.ql.io.RCFileOutputFormat';

It throws the following Error:

 Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row {"tmp_values_col1":"key1","tmp_values_col2":"nos","tmp_values_col3":"type1","tmp_values_col4":"2016-06-08 00:00:00","tmp_values_col5":"2016-08-04 01:01:01"}
	at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:179)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row {"tmp_values_col1":"key1","tmp_values_col2":"nos","tmp_values_col3":"type1","tmp_values_col4":"2016-06-08 00:00:00","tmp_values_col5":"2016-08-04 01:01:01"}
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:507)
	at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:170)
	... 8 more
Caused by: java.lang.UnsupportedOperationException: Currently the writer can only accept BytesRefArrayWritable
	at org.apache.hadoop.hive.ql.io.RCFile$Writer.append(RCFile.java:1110)
	at org.apache.hadoop.hive.ql.io.RCFileOutputFormat$2.write(RCFileOutputFormat.java:141)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:695)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
	at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:84)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
	at org.apache.hadoop.hive.ql.exec.TableScanOperator.processOp(TableScanOperator.java:95)
	at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.forward(MapOperator.java:157)
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:497)
	... 9 more

We need to get these error details along with the Operation Error message

**Comment by schaffino** [comment]
This is a feature we've been wanting for a long time as it would help our operations teams identify root cause of issue's much faster.

**Comment by wesm** [comment]
This is a relatively straightforward fix. I would happily accept a pull request; I've been buried with work on other projects so haven't been able to get to it yet.

**Comment by schaffino** [comment]
I might be missing some other way of getting this info but it looks like this might not be so simple due to https://issues.cloudera.org/browse/IMPALA-1633. In currently released versions of impala the error message does not get returned when calling GetOperationStatus. The status changes as below but we don't have any accompanying message.

`GetOperationStatus: resp=TGetOperationStatusResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), operationState=5, errorMessage=None, sqlState=None, errorCode=None)`

However, for queries that return results (which includes inserts and create table statements as they return the number of rows inserted) it does seem that a subsequent call to FetchResults returns the desired errorMessage.

`
FetchResults: resp=TFetchResultsResp(status=TStatus(errorCode=None, errorMessage='\nMemory limit exceeded\nThe memory limit is set too low to initialize spilling operator (id=3). The minimum required memory to spill this operator is 264.00 MB.\n', sqlState='HY000', infoMessages=None, statusCode=3), results=None, hasMoreRows=None)
`

The above errors have been forced with 
imp_cur.execute("set mem_limit=1")
and a simple query

I've made the following changes which support giving more detailed errors with current impala versions and also support the fix in impala 2.7.

https://github.com/schaffino/impyla/commit/cea034545611127945114e8d57d1bc122e8db1ba

Unfortunately it seems the above fix itself comes with it's own problems. The FetchResults immediately invalidates the query handle so subsequent calls to the cursor that rely on this will break (get_log, get_profile). 

For certain errors the errorMessage returned by hs2 isn't very useful and the logs returned by get_log actually contain root cause.

Take the below Exception received on a full scratch space.

`
impala.error.HiveServer2Error:
Cancelled
`

Retrieving logs for the query however returns something useful.

`
Query bc457b044ecc831f:850550e3a5743aab: 3% Complete (442 out of 11077)
fwrite(buffer, 1, 8388608, /tmp/impala-scratch/bc457b044ecc831f:850550e3a5743aab_7fee1b6d-76c7-485d-97ef-a58e0e366e47) failed with errno=28 description=Error(28): No space left on device (1 of 2 similar)
`

To get both with my above fix would mean adding in calls to get_log within the _wait_to_finish function and along with some other behavior changing i'm not sure that's the best solution.

Maybe just the following change and waiting for impala 2.7 is more sensible
https://github.com/schaffino/impyla/commit/4c56700a34055b3efd297e7c260adfd786a2ec59?diff=split

As 2.7 isn't released I couldn't test the above either so i'm not really sure whats the best way to go on this.

Anyway people can currently get detailed error messages with the existing impyla with some simple wrapper code around execute.
i.e
```python
#Include OperationalError exception
from impala.error import OperationalError
#Get cursor
try:
    imp_cur.execute('some sql')
except OperationalError, err:
    if (err.message=='Operation is in ERROR_STATE' and 
                                                    imp_cur.has_result_set ):
        print imp_cur.get_log()
        if imp_cur.has_result_set:
             imp_cur._last_operation_active=False
             imp_cur._last_operation.fetch()
        else:
            raise
    else:
        print imp_cur.get_log()
        raise
````

**Comment by FlorianWilhelm** [comment]
@schaffino Thanks for posting that code but could you please explain a bit more what it actually does? What I don't get is the nested if ... else clause. At that point imp_cur.has_result_set should be always true because the outer if guarantees exactly that, so the _last_operation ist set to inactive, we fetch and just go on without reraising? Could you please elaborate more on that? Does that mean there was an error but it is not that important? Why don't we return the result of fetch()? Thank you!

**Comment by schaffino** [comment]
@FlorianWilhelm 
Hi Florian,
You're right, the if else in there is superfluous. Chalk that bit up to a late night :). It was just meant to be a quick example of how you can get a more meaningful error message with the internal fetch call using the current impyla version.  The below makes more sense.

```python
from impala.error import OperationalError
#Get cursor
try:
    imp_cur.execute('some sql')
except OperationalError, err:
    if (err.message=='Operation is in ERROR_STATE' and 
                                                    imp_cur.has_result_set ):
        print imp_cur.get_log()
        imp_cur._last_operation_active=False
        imp_cur._last_operation.fetch()
    else:
        print imp_cur.get_log()
        raise
```

The reason we don't do anything with that fetch is because it never returns successfully. Because the query is in an error state already an exception is always raised on that fetch attempt and it is the second exception that usually includes a more detailed error message.

When you call fetch and the current operation is in an error state this has the side effect of making the query finalise as far as the daemon is concerned and invalidates the query handle. If you don't modify imp_cur._last_operation_active to False, when you try and use the same cursor again to run a another query, impyla's internal code will try and close the previous operation and you will get an 'invalid query handle' exception. Setting imp_cur._last_operation_active=False means that if code similar to the above was in a function and you are passing round a cursor, if you were to catch and log any exception, using the same cursor again will not immediately cause another exception.

**Comment by FlorianWilhelm** [comment]
@schaffino Thanks a lot for your explanation! I will use this code in my projects until this is directly fixed inside impyla, thank you.

**Comment by wesm** [comment]
Any possibility of putting in a pull request?

**Comment by FlorianWilhelm** [comment]
@schaffino I got an error lately but the code above actually resulted in

    AttributeError: 'OperationalError' object has no attribute 'message'

Am I doing something wrong here?

**Comment by FlorianWilhelm** [comment]
@schaffino Okay, just googled that :-) The attribute ``.message`` on an exception object seems to be deprecated since Python 2.6 and I am actually using Python 3.5. So I guess your code should be changed to use ``.args[0]`` instead of ``.message``, right? 

[BaseException.message has been deprecated as of Python 2.6](http://stackoverflow.com/questions/1272138/baseexception-message-deprecated-in-python-2-6)

**Comment by FlorianWilhelm** [comment]
Well and after fixing the ``.message`` issue I got:

>   File "/media/home/fwilhelm/Sources/hive-utils/hive_utils/query.py", line 84, in _execute
    _logger.error(self._cursor.get_log())
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/impala/hiveserver2.py", line 466, in get_log
    return self._last_operation.get_log()
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/impala/hiveserver2.py", line 1009, in get_log
    return self._rpc('GetLog', req).log
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/impala/hiveserver2.py", line 815, in _rpc
    response = self._execute(func_name, request)
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/impala/hiveserver2.py", line 832, in _execute
    return func(request)
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/thriftpy/thrift.py", line 160, in _req
    return self._recv(_api)
  File "/media/home/fwilhelm/miniconda3/envs/hive/lib/python3.5/site-packages/thriftpy/thrift.py", line 177, in _recv
    raise x
thriftpy.thrift.TApplicationException: Invalid method name: 'GetLog'

**Comment by FlorianWilhelm** [comment]
According to [this Hive patch](https://issues.apache.org/jira/browse/HIVE-4629) ``GetLog`` was implemented in version 0.14 so maybe this a problem with [thriftpy](https://github.com/eleme/thriftpy)? Any ideas?

**Comment by schaffino** [comment]
#211 for fix to this issue post IMPALA-1633
@FlorianWilhelm that problem looks like it needs its own issue.

**Comment by schaffino** [comment]
@FlorianWilhelm 
Really useful addition. Thanks!
