### ISSUE TITLE
Error when connecting to hive 

### ISSUE THREAD

**Issue by tobereborn** [cloudera/impyla#249]
Hi, i am running impyla python client as follow, however  no attribute error raises, Could anyone advice on this? 

    conn = connect(host='localhost',
                   user='xxx',
                   password='xxx',
                   database='test',
                   port=10000,
                   auth_mechanism='PLAIN')
    cur = conn.cursor()
    cur.execute('select * from employee')
    rows = cur.fetchall()
    for row in rows:
        print(row)

Traceback (most recent call last):
  File "/home/weizhenjin/TbrGitHub/git/python-recipes/db/hive_impyla_query_with_fetchall.py", line 44, in <module>
    main()
  File "/home/weizhenjin/TbrGitHub/git/python-recipes/db/hive_impyla_query_with_fetchall.py", line 36, in main
    cur = conn.cursor()
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/hiveserver2.py", line 125, in cursor
    session = self.service.open_session(user, configuration)
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/hiveserver2.py", line 995, in open_session
    resp = self._rpc('OpenSession', req)
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/hiveserver2.py", line 923, in _rpc
    response = self._execute(func_name, request)
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/hiveserver2.py", line 940, in _execute
    return func(request)
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 175, in OpenSession
    return self.recv_OpenSession()
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 193, in recv_OpenSession
    result.read(self._iprot)
  File "/opt/anaconda/anaconda3/envs/drp01/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 1109, in read
    fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
AttributeError: 'TSaslClientTransport' object has no attribute 'trans'

**Comment by cricket007** [comment]
Duplicate #235 

    pip install thrift=0.9.3
