### ISSUE TITLE
Connecting to impala from an external machine.

### ISSUE THREAD

**Issue by krishnakt031990** [cloudera/impyla#255]
Hello,

Has any one here tried out connecting to impala from an external machine? My cluster is kerberized and uses TLS. I have been trying to connect to impala using impyla

connect(host='**hostname**', port=21050, use_ssl=True, ca_cert='xxxx.pem', auth_mechanism='GSSAPI' , kerberos_service_name='xxxx@yyy.local')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/usr/lib/python2.7/site-packages/impala/hiveserver2.py", line 658, in connect
    transport.open()
  File "/usr/lib64/python2.7/site-packages/thrift/transport/TTransport.py", line 149, in open
    return self.__trans.open()
  File "/usr/lib64/python2.7/site-packages/thrift/transport/TSSLSocket.py", line 120, in open
    self._validate_cert()
  File "/usr/lib64/python2.7/site-packages/thrift/transport/TSSLSocket.py", line 157, in _validate_cert
    'provided commonName "%s"' % (self.host, certhost))
thrift.transport.TTransport.TTransportException: Hostname we connected to "**hostname**" doesn't match certificate provided commonName "xyz.yyy.local"

I have verified my cert chain is correct. 

Thanks in advance

**Comment by nateinindy** [comment]
We are now being forced to TLS and are finding the exact same error.  Were you ever able to fix?

**Comment by krishnakt031990** [comment]
Yes, we had a work around by working with the TSSLSocket.py itself
