### ISSUE TITLE
Can not connect Kerberos Enabled HiveServer2

### ISSUE THREAD

**Issue by ufukomer** [cloudera/impyla#306]
Trying to connect from host machine to CDH VBox Kerberos Enabled Impala. `impala-shell -k` command works perfectly but I can not connect via impyla:

```shell
Traceback (most recent call last):
  File "yarasa.py", line 2, in <module>
    conn = connect(host='127.0.0.1', port=21050, auth_mechanism='GSSAPI', kerberos_service_name='impala')
  File "/Library/Python/2.7/site-packages/impyla-0.13.6-py2.7.egg/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/Library/Python/2.7/site-packages/impyla-0.13.6-py2.7.egg/impala/hiveserver2.py", line 658, in connect
    transport.open()
  File "/Library/Python/2.7/site-packages/thrift_sasl/__init__.py", line 72, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)
```

These are principals:

<img width="664" alt="screen shot 2018-06-17 at 9 04 40 pm" src="https://user-images.githubusercontent.com/7649229/41510715-16b381e0-7272-11e8-983a-70f5b3f94ff7.png">

klist:

<img width="625" alt="screen shot 2018-06-17 at 9 05 04 pm" src="https://user-images.githubusercontent.com/7649229/41510727-3100e0c4-7272-11e8-8ab7-d672b6a71565.png">

**Comment by ufukomer** [comment]
https://stackoverflow.com/questions/50914705/can-not-connect-kerberos-enabled-hiveserver2-no-credentials-cache-file-found

**Comment by ashpad** [comment]
Tried all options no luck
was anyone able to get this to work

connect( host='<loadbalancerip>', port=21050,kerberos_service_name='impala', auth_mechanism='GSSAPI',use_ssl=True,ca_cert='path/to/jks')


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/usr/lib/python2.7/site-packages/impala/hiveserver2.py", line 758, in connect
    transport.open()
  File "/usr/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 61, in open
    self._trans.open()
  File "/usr/lib64/python2.7/site-packages/thrift/transport/TSSLSocket.py", line 118, in open
    message=message)
