### ISSUE TITLE
thriftpy.transport.TTransportException: TTransportException(type=1, message="Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: Unable to find a callback: 2'")

### ISSUE THREAD

**Issue by HQBhoho** [cloudera/impyla#315]
conn = connect(host='ut01.hbzq.com', port=10000,auth_mechanism='GSSAPI',database='dwd',kerberos_service_name='hive' )
it's ok work on Linux ,But  fail on windows,I hava install kerberos client on windows.The errorMessage show as title.
detail:
Traceback (most recent call last):
  File "E:/pythonProjects/jdbc-client/clinet/impala_client.py", line 11, in <module>
    database='dwd', kerberos_service_name='impala'
  File "D:\SoftWare\Anaconda3\lib\site-packages\impala\dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "D:\SoftWare\Anaconda3\lib\site-packages\impala\hiveserver2.py", line 658, in connect
    transport.open()
  File "D:\SoftWare\Anaconda3\lib\site-packages\thrift_sasl\__init__.py", line 72, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thriftpy.transport.TTransportException: TTransportException(type=1, message="Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: Unable to find a callback: 2'")

**Comment by rkrishnan2012** [comment]
Make sure to run kinit before connecting.

**Comment by HQBhoho** [comment]
I hava install kerberos client on windows.And I use 'os.system(kinit -kt xxx.keytab xxx)' in my code.It's fine on Linux but error on windows.
six bit_array thriftpy  thrift_sasl sasl impyla ,these all install on my windows.

**Comment by cwj** [comment]
Do someone knows how to solve this issue?

**Comment by Kim-Taesu** [comment]
in my case 
```
pip uninstall pure-sasl
pip uninstall sasl
pip install pure-sasl
```

and execute your code
---
reference : https://github.com/cloudera/impyla/issues/267#issuecomment-334389532
