### ISSUE TITLE
impyla Kerberos No success 

### ISSUE THREAD

**Issue by ashpad** [cloudera/impyla#323]
Hi All - Has anyone been able to successfully connect to a kerberized cluster? I have gone through many tries and still unsuccessful.

conn=connect( host=impalaloadbalancer, port=21050,kerberos_service_name='impala', auth_mechanism='GSSAPI',use_ssl=True,ca_cert='ca-certs.jks')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/usr/lib/python2.7/site-packages/impala/hiveserver2.py", line 758, in connect
    transport.open()
  File "/usr/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 61, in open
    self._trans.open()
  File "/usr/lib64/python2.7/site-packages/thrift/transport/TSSLSocket.py", line 118, in open
    message=message)
thrift.transport.TTransport.TTransportException: Could not connect to <impalaloadbalancer>:21050: unknown error (_ssl.c:2782)

**Comment by gregrahn** [comment]
For my setup I first `kinit` then use
```
conn = connect(
    host='impala.co.com',
    port=21050,
    use_ssl=True,
    auth_mechanism='GSSAPI',
    kerberos_service_name='impala')
```

**Comment by ashpad** [comment]
Approach with impyla and kerberos @gregrahn can we add this to examples
```
from impala.dbapi import connect
conn=connect(host='impalahostHA.example.com', port=21050,kerberos_service_name='impala', auth_mechanism='GSSAPI',use_ssl=True,ca_cert='ca-certs.pem')
cursor = conn.cursor()
cursor.execute('show databases')
print (cursor.description)
```

**Comment by gregrahn** [comment]
@ashpad - you can certainly submit a pull request with any additions to the examples that you think are useful to impyla users
