### ISSUE TITLE
OpenSession

### ISSUE THREAD

**Issue by cun123** [cloudera/impyla#368]
thrift.Thrift.TApplicationException: Invalid method name: 'OpenSession'

help me!

**Comment by timarmstrong** [comment]
If you're reporting a bug, please provide steps to reproduce.

You're probably connecting to the wrong thrift service, but we can't help you with no information about what you're doing.

**Comment by cun123** [comment]
# -*- coding=utf-8 -*-

from impala.dbapi import connect

#impala
conn = connect(host='xx.xx.xx.xx', port=25003, user='xx', password='xx', auth_mechanism='PLAIN')
#conn=connect(host='xx.xx.xx.xx',port=25003,auth_mechanism='PLAIN')

cur = conn.cursor()

cur.execute("use xx")

cur.execute('''
    show create table xx
''')
for row in cur:
    print(row[0])
print('-------------------------------------------------------------------------------------------')

cur.close()
conn.close()

**Comment by cun123** [comment]
cur = conn.cursor()  ----------> An error occurs

**Comment by cun123** [comment]
Traceback (most recent call last):
  File "test_impala.py", line 9, in <module>
    cur = conn.cursor()
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/hiveserver2.py", line 105, in cursor
    session = self.service.open_session(user, configuration)
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/hiveserver2.py", line 887, in open_session
    resp = self._rpc('OpenSession', req)
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/hiveserver2.py", line 815, in _rpc
    response = self._execute(func_name, request)
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/hiveserver2.py", line 832, in _execute
    return func(request)
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/_thrift_gen/TCLIService/TCLIService.py", line 175, in OpenSession
    return self.recv_OpenSession()
  File "/usr/lib/python2.6/site-packages/impyla-0.13.8-py2.6.egg/impala/_thrift_gen/TCLIService/TCLIService.py", line 191, in recv_OpenSession
    raise x
thrift.Thrift.TApplicationException: Invalid method name: 'OpenSession'

**Comment by timarmstrong** [comment]
You're probably connecting to the beeswax port on the impala daemon (21000) instead of the HS2 port (21050). I'm guessing you're going via a load balancer. See https://docs.cloudera.com/documentation/enterprise/latest/topics/impala_ports.html for a reference on Impala's ports.

This isn't an Impyla bug.

**Comment by cun123** [comment]
Thanks for your help
