### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by zhouxm** [cloudera/impyla#382]
impyla==0.14.2.2 
thrift==0.13.0    
thrift-sasl==0.4.0     
thriftpy==0.3.9     
thriftpy2==0.4.10

[2020-01-10T07:12:48] - [hiveserver2.py:943][ERROR]: Failed to open transport (tries_left=2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/impala/hiveserver2.py", line 940, in _execute
    return func(request)
  File "/usr/local/lib64/python3.6/site-packages/thriftpy/thrift.py", line 195, in _req
    self._send(_api, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/thriftpy/thrift.py", line 207, in _send
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 143, in flush
    self._flushPlain(buffer)
  File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 166, in _flushPlain
    self._trans.write(struct.pack(">I", len(buffer)) + buffer)
  File "/usr/local/lib64/python3.6/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 401, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 395, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 382, in _send_loop
    return send_method(data, *args)
OSError: [Errno 9] Bad file descriptor

**Comment by zhouxm** [comment]
thrift==0.13.0   
thrift-sasl==0.4.0    
thriftpy==0.3.9    
thriftpy2==0.4.0 
impyla==0.16.1  

 File "/data/venv/lib/python3.6/site-packages/impyla-0.16.1-py3.6.egg/impala/hiveserver2.py", line 1191, in get_log
    log = self._rpc('GetLog', req).log
  File "/data/venv/lib/python3.6/site-packages/impyla-0.16.1-py3.6.egg/impala/hiveserver2.py", line 992, in _rpc
    response = self._execute(func_name, request)
  File "/data/venv/lib/python3.6/site-packages/impyla-0.16.1-py3.6.egg/impala/hiveserver2.py", line 1009, in _execute
    return func(request)
  File "/data/venv/lib/python3.6/site-packages/thriftpy2/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/data/venv/lib/python3.6/site-packages/thriftpy2/thrift.py", line 215, in _recv
    raise x
thriftpy2.thrift.TApplicationException: Invalid method name: 'GetLog'
