### ISSUE TITLE
impyla with LDAP auth encounter a hang during executing 

### ISSUE THREAD

**Issue by dacoolbaby** [cloudera/impyla#392]
We are using impyla v0.16.1 on both windows and linux to connect Impala with LDAP auth.
Noticed that impyla conmponent with LDAP auth required thrift_sasl module which we consider something bad happens here.

Running execution is fine without LDAP auth, and encounter a hang utill timeout with LDAP auth.

Finally, we try pyhive instead and all the selection with or without LDAP return normal.

pls have a look.

**Comment by timarmstrong** [comment]
@dacoolbaby there's probably not enough information here for us to reproduce the problem. Can you report the version of Impala that you're running, the OS versions, and an example of how you're connecting. If you can get a backtrace of where the python thread is hanging too that would be helpful.

**Comment by dacoolbaby** [comment]
More details as follow:


Impala version is :&nbsp;CDH-6.3.0-1.cdh6.3.0.p0.1279813
Linux version 3.10.0-1062.4.1.el7.x86_64
CentOS Linux release 7.7.1908


running jdbc on java driver is ok. And now the pyhive also get hang problem too.


Python Side traceback as follow, process was stop by timeout.


Traceback (most recent call last):
&nbsp; File "C:/Users/daxin/PycharmProjects/Demo/impala_demo/hive_ldap_demo2.py", line 19, in <module&gt;
&nbsp; &nbsp; results = cursor.fetchall()
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 535, in fetchall
&nbsp; &nbsp; return list(self)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 583, in __next__
&nbsp; &nbsp; convert_types=self.convert_types)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 1242, in fetch
&nbsp; &nbsp; resp = self._rpc('FetchResults', req)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 994, in _rpc
&nbsp; &nbsp; err_if_rpc_not_ok(response)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 748, in err_if_rpc_not_ok
&nbsp; &nbsp; raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: Invalid query handle: 604c103afc754c09:3e40f2d100000000


Thansk!!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Armstrong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午10:46
收件人:&nbsp;"cloudera/impyla"<impyla@noreply.github.com&gt;;
抄送:&nbsp;"星宇-Sam-"<daxingyu@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudera/impyla] impyla with LDAP auth encounter a hang during executing  (#392)





 
@dacoolbaby there's probably not enough information here for us to reproduce the problem. Can you report the version of Impala that you're running, the OS versions, and an example of how you're connecting. If you can get a backtrace of where the python thread is hanging too that would be helpful.

**Comment by dacoolbaby** [comment]
Now the hanging is only exists on windows.
We will do a lot more test to confirm.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"星宇-Sam-"<daxingyu@qq.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午11:02
收件人:&nbsp;"cloudera/impyla"<reply@reply.github.com&gt;;"cloudera/impyla"<impyla@noreply.github.com&gt;;
抄送:&nbsp;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;回复： [cloudera/impyla] impyla with LDAP auth encounter a hang during executing  (#392)



More details as follow:


Impala version is : CDH-6.3.0-1.cdh6.3.0.p0.1279813
Linux version 3.10.0-1062.4.1.el7.x86_64
CentOS Linux release 7.7.1908


running jdbc on java driver is ok. And now the pyhive also get hang problem too.


Python Side traceback as follow, process was stop by timeout.


Traceback (most recent call last):
&nbsp; File "C:/Users/daxin/PycharmProjects/Demo/impala_demo/hive_ldap_demo2.py", line 19, in <module&gt;
&nbsp; &nbsp; results = cursor.fetchall()
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 535, in fetchall
&nbsp; &nbsp; return list(self)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 583, in __next__
&nbsp; &nbsp; convert_types=self.convert_types)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 1242, in fetch
&nbsp; &nbsp; resp = self._rpc('FetchResults', req)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 994, in _rpc
&nbsp; &nbsp; err_if_rpc_not_ok(response)
&nbsp; File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\impala\hiveserver2.py", line 748, in err_if_rpc_not_ok
&nbsp; &nbsp; raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: Invalid query handle: 604c103afc754c09:3e40f2d100000000


Thansk!!


&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"Tim Armstrong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午10:46
收件人:&nbsp;"cloudera/impyla"<impyla@noreply.github.com&gt;;
抄送:&nbsp;"星宇-Sam-"<daxingyu@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudera/impyla] impyla with LDAP auth encounter a hang during executing  (#392)





 
@dacoolbaby there's probably not enough information here for us to reproduce the problem. Can you report the version of Impala that you're running, the OS versions, and an example of how you're connecting. If you can get a backtrace of where the python thread is hanging too that would be helpful.

**Comment by dacoolbaby** [comment]
Ok,we solve it by using selection without using "*" . We found that the query sql using * will causing the execution hang with LDAP auth. But I think it is still a bug.

**Comment by dacoolbaby** [comment]
but on the production env, we still encounter hang.

Traceback (most recent call last):
  File "C:/Users/daxin/PycharmProjects/Demo/impala_demo/pyhive_demo.py", line 25, in <module>
    print(cur.fetchall())
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyhive\common.py", line 136, in fetchall
    return list(iter(self.fetchone, None))
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyhive\common.py", line 105, in fetchone
    self._fetch_while(lambda: not self._data and self._state != self._STATE_FINISHED)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyhive\common.py", line 45, in _fetch_while
    self._fetch_more()
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyhive\hive.py", line 386, in _fetch_more
    response = self._connection.client.FetchResults(req)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\TCLIService.py", line 714, in FetchResults
    return self.recv_FetchResults()
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\TCLIService.py", line 733, in recv_FetchResults
    result.read(iprot)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\TCLIService.py", line 3470, in read
    self.success.read(iprot)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\ttypes.py", line 6583, in read
    self.results.read(iprot)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\ttypes.py", line 2867, in read
    _elem115.read(iprot)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\ttypes.py", line 2741, in read
    self.stringVal.read(iprot)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\TCLIService\ttypes.py", line 2521, in read
    _elem95 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\thrift\protocol\TProtocol.py", line 185, in readString
    return binary_to_str(self.readBinary())
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 233, in readBinary
    self._check_string_length(size)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 47, in _check_string_length
    self._check_length(self.string_length_limit, length)
  File "C:\Users\daxin\AppData\Local\Programs\Python\Python37\lib\site-packages\thrift\protocol\TProtocol.py", line 59, in _check_length
    'Negative length: %d' % length)
thrift.transport.TTransport.TTransportException: Negative length: -393172762

**Comment by dacoolbaby** [comment]
We still encounter hang at the production env.
When the sql running selection on table column ,it just hang. But if you run count query ,return ok.

**Comment by dacoolbaby** [comment]
we finally solved the problem by replacing the dependencies module as follow:
thriftpy                                                      0.3.9
thriftpy2                                                    0.4.10
thrift                                                          0.9.3
thrift-sasl                                                0.2.1
sasl                                                              0.2.1
thrift-sasl                                                0.2.1
impyla                                                   0.16.2

**Comment by noklam** [comment]
@dacoolbaby Did you figure out what was the issue? I am getting the same error on Window.

**Comment by anth0ny-x** [comment]
My query was hanging with both auth_mechanism='LDAP' and auth_mechanism='PLAIN', Solved it by downgrading to thrift-sasl 0.4.2 -> 0.2.1 after seeing dacoolbaby's  comment

**Comment by noklam** [comment]
@anth0ny-x can u share the library version like `pip list`?

it seems only a specific version can work.

are u able to connect stably ? As I can connect but it will often hangs after few query.

**Comment by anth0ny-x** [comment]
I'm running Ubuntu 18.04.4 LTS and my pip list
impyla (0.16.2)
sasl (0.2.1)
thrift (0.13.0)
thrift-sasl (0.2.1)
thriftpy (0.3.9)
thriftpy2 (0.4.11)

**Comment by yuanhunglo** [comment]
Downgrading thrift-sasl 0.4.2 --> 0.2.1 worked for me.
