### ISSUE TITLE
AuthorizationException when I try to connect db

### ISSUE THREAD

**Issue by allen1106** [cloudera/impyla#393]
# version
 - python3.6
 - impyla==0.15.0
 - thrift==0.13.0
 - thrift-sasl==0.4.2
# code
```
from impala.dbapi import connect
conn = connect(host='<host>', port=<port>, user='<username>', database='<db>')
cursor = conn.cursor()
```
# error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 139, in cursor
    cursor.execute('USE %s' % self.default_db)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 310, in execute
    configuration=configuration)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 351, in execute_async
    self._execute_async(op)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 370, in _execute_async
    operation_fn()
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 348, in op
    run_async=True)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 1048, in execute
    return self._operation('ExecuteStatement', req)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 978, in _operation
    resp = self._rpc(kind, request)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 946, in _rpc
    err_if_rpc_not_ok(response)
  File "/home/xxxxxx/superset36/lib/python3.6/site-packages/impala/hiveserver2.py", line 719, in err_if_rpc_not_ok
    raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: AuthorizationException: User 'xxxxxx' does not have privileges to access: <db>.*
```
# conclusion
It seems it can't parse the user in parmas(`conn = connect(host='<host>', port=<port>, user='<username>', database='<db>')`), so it use the host username

And then, I try to set user in `cursor`, like this:
```
from impala.dbapi import connect
conn = connect(host='<host>', port=<port>, user='<username>', database='<db>')
cursor = conn.cursor(user='<username>')
```
It works well

**Comment by allen1106** [comment]
I checked the source code, and I found in NOSASL mode, it use the pure socket connection to connect impala without user & password. And then, impala side will fetch the host server user to do authentication. So, if you want to use NOSASL mode, you'd better to be sure your host user have the permission to access the target impala.

But for me, I want to control the user by sqlalchemy uri, so I change my impyla code. Set the user from uri in `cursor` function. It might be a ugly way, does anyone have another gentle one?

**Comment by MerouaneBen** [comment]
facing the same issue, don't know if there a clean way to use username and password in URI
