### ISSUE TITLE
I'm Failing to connect to Hive server

### ISSUE THREAD

**Issue by nourou4them** [cloudera/impyla#417]
Hi,

After installing the necessary libraries and installing `impyla`, I tried to run a test with the following code : 
`from impala.dbapi import connect`
`conn = connect(host='host_url', port=10000, auth_mechanism='GSSAPI', kerberos_service_name='hive')`
`cursor = conn.cursor()`
`cursor.execute('some random sql query')`
`print (cursor.description)  # prints the result set's schema`
`results = cursor.fetchall()`

This is the message I have : 
`Traceback (most recent call last):`
  `File "P:\***\test_impyla0.py", line 3, in <module>`
    `conn = connect(host='host_url', port=10000, auth_mechanism='GSSAPI', kerberos_service_name='hive')`
  `File "C:\Users\***\PycharmProjects\impyla\venv\lib\site-packages\impyla-0.16.2-py3.7.egg\impala\dbapi.py", line 150, in connect`
    `http_path=http_path)`
  `File "C:\Users\***\PycharmProjects\impyla\venv\lib\site-packages\impyla-0.16.2-py3.7.egg\impala\hiveserver2.py", line 825, in connect`
    `transport.open()`
`File "C:\Users\***\PycharmProjects\impyla\venv\lib\site-packages\thrift_sasl-0.4.2-py3.7.egg\thrift_sasl\__init__.py", line 96, in open
**thrift.transport.TTransport.TTransportException: Bad status: 3 (b'Problem with callback handler**')`

I have tried to search for solutions and I am still stucks.

**Comment by mishra2611** [comment]
A little late to comment here, but posting for future readers: `kerberos_service_name='hive', auth_mechanism='PLAIN', use_http_transport=True` worked for me

**Comment by nourou4them** [comment]
I am not working on thi subject anymore, so I can't really test it right now.
Thanks for your comment anyway.
