### ISSUE TITLE
GSSAPI Error:  Miscellaneous failure (see text (Error from KDC: PROCESS_TGS) with MacOs BigSur

### ISSUE THREAD

**Issue by mehmetozanguven** [cloudera/impyla#428]
- Before upgrading to the BigSur, I can easily run the script to connect the impala via kerberos auth, there was no issue at all.
- After upgrading, (this is so interesting) The same script can sometimes connect and print the result but most of time  it gives me an error. Here is the error:
```python
   message=("Could not start SASL: %s" % self.sasl.getError()))
thriftpy.transport.TTransportException: TTransportException(type=1, message="Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Error from KDC: PROCESS_TGS)'")
```

- Here is simple code to test the connection to impala:
```python
from impala.dbapi import connect

conn = connect(host='host', port=21050,auth_mechanism='GSSAPI',kerberos_service_name='impala')
cursor = conn.cursor()
cursor.execute('show tables')
print(cursor.description)
results = cursor.fetchall()
for p in results:
     print(p)
```
Is there anyone facing with the same problem ?

**Comment by jmadison222** [comment]
I have something similar.  If I have any data set over a trivial size, I can't even fetchone()

Traceback (most recent call last):
  File "/export/home/jm/Linux/see/see.py", line 159, in <module>
    objMain.main()
  File "/export/home/jm/Linux/see/see.py", line 98, in main
    df = factory.getDf(self.theArgs)
  File "/tech/home/jm/Linux/see/dfGetterFactory.py", line 23, in getDf
    return getter.getDf(args)
  File "/tech/home/jm/Linux/see/hive.py", line 43, in getDf
    row = cursor.fetchone()
  File "/export/home/jm/.local/lib/python3.6/site-packages/impala/hiveserver2.py", line 478, in fetchone
    return next(self)
  File "/export/home/jm/.local/lib/python3.6/site-packages/impala/hiveserver2.py", line 584, in __next__
    convert_types=self.convert_types)
  File "/export/home/jm/.local/lib/python3.6/site-packages/impala/hiveserver2.py", line 1266, in fetch
    resp = self._rpc('FetchResults', req)
  File "/export/home/jm/.local/lib/python3.6/site-packages/impala/hiveserver2.py", line 993, in _rpc
    response = self._execute(func_name, request)
  File "/export/home/jm/.local/lib/python3.6/site-packages/impala/hiveserver2.py", line 1010, in _execute
    return func(request)
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thriftpy2/thrift.py", line 219, in _req
    return self._recv(_api)
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thriftpy2/thrift.py", line 231, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 373, in read_message_begin
    self.trans, strict=self.strict_read)
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 165, in read_message_begin
    sz = unpack_i32(inbuf.read(4))
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 173, in read
    self._read_frame()
  File "/usr/app/anaconda_3/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 187, in _read_frame
    message=self.sasl.getError())
thrift.transport.TTransport.TTransportException: b'Error in sasl_decode (-1) SASL(-1): generic failure: Unable to find a callback: 32775'

Connection code is:
        conn = connect(
            host=os.environ['hiveServer'],
            port=10000,
            auth_mechanism='GSSAPI',
            kerberos_service_name='hive'
        )
