### ISSUE TITLE
Impyla breaks with newer version of bitarray (2.1.0)

### ISSUE THREAD

**Issue by emilyreff7** [cloudera/impyla#450]
Our CI in ibis started to break with the following errors when bitarray got bumped to 2.1.0:

```
Traceback (most recent call last):
  File "ci/impalamgr.py", line 15, in <module>
    from ibis.backends.impala.tests.conftest import IbisTestEnv
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/__init__.py", line 6, in <module>
    from .client import (  # noqa: F401
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/client.py", line 43, in <module>
    from .compat import HS2Error, ImpylaError, impyla
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/compat.py", line 15, in <module>
    import impala.dbapi as impyla  # noqa
  File "/usr/share/miniconda/site-packages/impala/dbapi.py", line 28, in <module>
    import impala.hiveserver2 as hs2
  File "/usr/share/miniconda/site-packages/impala/hiveserver2.py", line 26, in <module>
    from bitarray import bitarray
  File "/usr/share/miniconda/site-packages/bitarray/__init__.py", line 14, in <module>
    from bitarray._bitarray import (bitarray, decodetree, _sysinfo,
ModuleNotFoundError: No module named 'bitarray._bitarray'
```

Any ideas about this?
We have pinned to bitarray 2.0.1 in the meantime: https://github.com/ibis-project/ibis/pull/2781

**Comment by csringhofer** [comment]
#588 unpinned bitarray. Closing this issue/
