### ISSUE TITLE
Error in Python 3.12.1 trying to run connect

### ISSUE THREAD

**Issue by jmagana2000** [cloudera/impyla#529]
Got this exception when trying to create a connect object when running in Docker container using Ubuntu 22.04 and Python 3.12.1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/impala/dbapi.py", line 197, in connect
    service = hs2.connect(host=host, port=port,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/impala/hiveserver2.py", line 865, in connect
    transport.open()
  File "/usr/lib/python3.12/site-packages/thrift/transport/TTransport.py", line 155, in open
    return self.__trans.open()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/impala/_thrift_api.py", line 174, in open
    self.__http = http_client.HTTPSConnection(self.host, self.port,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'

**Comment by csringhofer** [comment]
Merged https://github.com/cloudera/impyla/pull/531 so this should be solved.
