### ISSUE TITLE
Query create table with lot of fields don't work

### ISSUE THREAD

**Issue by jbarotin** [cloudera/impyla#53]
Hi, 

I'm working on the Cloudera single node Virtual Machine. I'm trying to create a table with lot of fields though the code bellow :

```python
# -*- coding: utf8 

from impala.dbapi import connect

conn = connect(host='localhost',
               port=21050)

cur = conn.cursor()

sql = '''CREATE TABLE row_table (a	smallint,
b	smallint,
c	smallint,
d	BIGINT,
e	SMALLINT,
f	 INT,
g	 INT,
h	SMALLINT,
i	 INT,
j	 INT,
k	 INT,
l	SMALLINT,
m	smallint,
n	 INT,
o	smallint,
p	 INT,
q	 BIGINT,
r	 BIGINT,
s	 BIGINT,
t	 BIGINT,
u	 BIGINT,
v	 BIGINT,
w	 BIGINT,
x	 BIGINT,
y	 BIGINT,
z	 BIGINT,
aa	 INT,
ab	 INT,
ac	 INT,
ad	 INT,
ae	 INT,
af	 INT,
ag	 INT,
ah	 INT,
ai	 INT,
aj	 INT,
ak	 INT,
al	 INT,
am	 INT,
an	 INT,
ao	 INT,
ap	 INT,
aq	 INT,
ar	 INT,
as	 INT,
at	 INT,
au	 INT,
av	 INT,
aw	 INT,
ax	 INT,
ay	smallint,
az	 BIGINT,
ba	 BIGINT,
bb	smallint,
bc	 BIGINT,
bd	 BIGINT,
be	smallint,
bf	smallint,
bg	 BIGINT,
bh	 BIGINT,
bj	smallint,
bk	 BIGINT,
bl	 BIGINT,
bm	STRING,
bn	STRING,
bo	STRING,
bp	STRING,
bq	STRING,
br	STRING,
bs	STRING,
bt	STRING,
bu	STRING,
bv	STRING,
bw	 INT,
bx	STRING,
by	STRING,
bz	STRING,
ca	 BIGINT,
cb	 BIGINT,
cc	smallint,
cd	smallint,
ce	STRING,
cf	smallint,
cg	 INT,
ch	smallint,
cj	 INT,
ck	smallint,
cl	smallint,
cm	smallint,
cn	smallint,
co	smallint,
cp	smallint,
cq	smallint,
cr	 INT,
cs	 INT,
ct	 INT,
cu	 INT,
cv	STRING,
cw	STRING,
cx	STRING,
cy	STRING,
cz	 BIGINT,
da	 BIGINT,
db	 BIGINT,
dc	 BIGINT,
dd	 BIGINT,
de	 BIGINT,
df	 BIGINT,
dg	 BIGINT,
dh	 BIGINT,
dj	 BIGINT,
dk	 INT,
dl	 INT,
dm	 INT,
dn	 INT,
do	 INT,
dp	 INT,
dq	 BIGINT,
dr	 BIGINT,
ds	 BIGINT,
dt	 BIGINT,
du	 BIGINT,
dv	 BIGINT,
dw	 BIGINT,
dx	 BIGINT,
dy	 BIGINT,
dz	 BIGINT,
ea	 BIGINT,
eb	 BIGINT,
ec	 BIGINT,
ed	 BIGINT,
ee	 BIGINT,
ef	 INT,
eg	 BIGINT,
eh	 BIGINT,
ej	 BIGINT,
ek	 BIGINT,
el	 BIGINT,
em	 BIGINT,
en	 BIGINT,
eo	 BIGINT,
ep	 BIGINT,
eq	 BIGINT,
er	 BIGINT,
es	 BIGINT,
et	 BIGINT,
eu	 BIGINT,
ev	 BIGINT,
ew	 BIGINT,
ex	 BIGINT,
ey	 BIGINT,
ez	 BIGINT,
fa	 BIGINT,
fb	 BIGINT,
fc	 BIGINT,
fd	 BIGINT,
fe	 BIGINT,
ff	 BIGINT,
fg	 BIGINT,
fh	 BIGINT,
fj	 BIGINT,
fk	 BIGINT,
fl	 BIGINT,
fm	 INT,
fn	 BIGINT,
fo	 BIGINT,
fp	 BIGINT,
fq	 BIGINT,
fr	 BIGINT,
fs	 BIGINT,
ft	 BIGINT,
fu	 BIGINT,
fv	 BIGINT,
fw	 BIGINT,
fx	 BIGINT,
fy	 BIGINT,
fz	 BIGINT,
gca	 BIGINT,
gcb	 BIGINT,
gcc	 BIGINT,
gcd	 BIGINT,
gce	 BIGINT,
gcf	 BIGINT,
gcg	 BIGINT,
gch	 BIGINT,
gcj	 BIGINT,
gck	 BIGINT,
gcl	 BIGINT,
gcm	 BIGINT,
gcn	STRING,
gco	STRING,
gcp	 INT,
gcq	 BIGINT,
gcr	 BIGINT,
gcs	 BIGINT,
gct	 BIGINT,
gcu	 BIGINT,
gcv	 INT,
gcw	 INT,
gcx	 INT,
gcy	 INT,
gcz	 INT,
ger	 INT,
get	 INT,
gey	 INT,
geu	 INT
) STORED AS PARQUET;'''
cur.execute(sql)
```

It doesn't work, it generate the following message :
```
Traceback (most recent call last):
  File "/home/cloudera/Public/base_big_data/base/test_big_query_impyla.py", line 219, in <module>
    cur.execute(sql)
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/dbapi.py", line 156, in execute
    self._execute_sync(op)
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/dbapi.py", line 162, in _execute_sync
    operation_fn()
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/dbapi.py", line 155, in op
    self.service, self.session_handle, self._last_operation_string)
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/rpc.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/rpc.py", line 203, in execute_statement
    err_if_rpc_not_ok(resp)
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/error.py", line 57, in err_if_rpc_not_ok
    raise RPCError("RPC status error: %s: %s" % (resp.__class__.__name__, str(resp.status)))
impala.error.RPCError: RPC status error: TExecuteStatementResp: TStatus(errorCode=None, errorMessage='AnalysisException: Syntax error in line 45:\nas\t INT,\n^\nEncountered: AS\nExpected: IDENTIFIER\n\nCAUSED BY: Exception: Syntax error', sqlState='HY000', infoMessages=None, statusCode=3)
```

If I copy and paste the create table query, in a file and execute it though "impala-shell -f query.txt" it work perfectly. So I'm thinking that's a trouble of the impyla library. 

What do you thinking about that ?

**Comment by laserson** [comment]
Two things:

* Get rid of the semicolon at the end of the statement.  It doesn't work with impyla.

* The error message itself makes it seem like Impala doesn't like the column name "as", since it looks like the keyword "AS".  Perhaps it needs to be quoted?

Try getting rid of the semicolon first, though.

**Comment by jbarotin** [comment]
Think a lot for your help, now it works. I needed to use quote and maybe not use semicolon as well.
Here it is my updated code :
````python
# -*- coding: utf8 

from impala.dbapi import connect

conn = connect(host='localhost',
               port=21050)

cur = conn.cursor()

sql = '''CREATE TABLE row_table (
`a`	smallint,
`b`	smallint,
`c`	smallint,
`d`	BIGINT,
`e`	SMALLINT,
`f`	 INT,
`g`	 INT,
`h`	SMALLINT,
`i`	 INT,
`j`	 INT,
`k`	 INT,
`l`	SMALLINT,
`m`	smallint,
`n`	 INT,
`o`	smallint,
`p`	 INT,
`q`	 BIGINT,
`r`	 BIGINT,
`s`	 BIGINT,
`t`	 BIGINT,
`u`	 BIGINT,
`v`	 BIGINT,
`w`	 BIGINT,
`x`	 BIGINT,
`y`	 BIGINT,
`z`	 BIGINT,
`aa`	 INT,
`ab`	 INT,
`ac`	 INT,
`ad`	 INT,
`ae`	 INT,
`af`	 INT,
`ag`	 INT,
`ah`	 INT,
`ai`	 INT,
`aj`	 INT,
`ak`	 INT,
`al`	 INT,
`am`	 INT,
`an`	 INT,
`ao`	 INT,
`ap`	 INT,
`aq`	 INT,
`ar`	 INT,
`as`	 INT,
`at`	 INT,
`au`	 INT,
`av`	 INT,
`aw`	 INT,
`ax`	 INT,
`ay`	smallint,
`az`	 BIGINT,
`ba`	 BIGINT,
`bb`	smallint,
`bc`	 BIGINT,
`bd`	 BIGINT,
`be`	smallint,
`bf`	smallint,
`bg`	 BIGINT,
`bh`	 BIGINT,
`bj`	smallint,
`bk`	 BIGINT,
`bl`	 BIGINT,
`bm`	STRING,
`bn`	STRING,
`bo`	STRING,
`bp`	STRING,
`bq`	STRING,
`br`	STRING,
`bs`	STRING,
`bt`	STRING,
`bu`	STRING,
`bv`	STRING,
`bw`	 INT,
`bx`	STRING,
`by`	STRING,
`bz`	STRING,
`ca`	 BIGINT,
`cb`	 BIGINT,
`cc`	smallint,
`cd`	smallint,
`ce`	STRING,
`cf`	smallint,
`cg`	 INT,
`ch`	smallint,
`cj`	 INT,
`ck`	smallint,
`cl`	smallint,
`cm`	smallint,
`cn`	smallint,
`co`	smallint,
`cp`	smallint,
`cq`	smallint,
`cr`	 INT,
`cs`	 INT,
`ct`	 INT,
`cu`	 INT,
`cv`	STRING,
`cw`	STRING,
`cx`	STRING,
`cy`	STRING,
`cz`	 BIGINT,
`da`	 BIGINT,
`db`	 BIGINT,
`dc`	 BIGINT,
`dd`	 BIGINT,
`de`	 BIGINT,
`df`	 BIGINT,
`dg`	 BIGINT,
`dh`	 BIGINT,
`dj`	 BIGINT,
`dk`	 INT,
`dl`	 INT,
`dm`	 INT,
`dn`	 INT,
`do`	 INT,
`dp`	 INT,
`dq`	 BIGINT,
`dr`	 BIGINT,
`ds`	 BIGINT,
`dt`	 BIGINT,
`du`	 BIGINT,
`dv`	 BIGINT,
`dw`	 BIGINT,
`dx`	 BIGINT,
`dy`	 BIGINT,
`dz`	 BIGINT,
`ea`	 BIGINT,
`eb`	 BIGINT,
`ec`	 BIGINT,
`ed`	 BIGINT,
`ee`	 BIGINT,
`ef`	 INT,
`eg`	 BIGINT,
`eh`	 BIGINT,
`ej`	 BIGINT,
`ek`	 BIGINT,
`el`	 BIGINT,
`em`	 BIGINT,
`en`	 BIGINT,
`eo`	 BIGINT,
`ep`	 BIGINT,
`eq`	 BIGINT,
`er`	 BIGINT,
`es`	 BIGINT,
`et`	 BIGINT,
`eu`	 BIGINT,
`ev`	 BIGINT,
`ew`	 BIGINT,
`ex`	 BIGINT,
`ey`	 BIGINT,
`ez`	 BIGINT,
`fa`	 BIGINT,
`fb`	 BIGINT,
`fc`	 BIGINT,
`fd`	 BIGINT,
`fe`	 BIGINT,
`ff`	 BIGINT,
`fg`	 BIGINT,
`fh`	 BIGINT,
`fj`	 BIGINT,
`fk`	 BIGINT,
`fl`	 BIGINT,
`fm`	 INT,
`fn`	 BIGINT,
`fo`	 BIGINT,
`fp`	 BIGINT,
`fq`	 BIGINT,
`fr`	 BIGINT,
`fs`	 BIGINT,
`ft`	 BIGINT,
`fu`	 BIGINT,
`fv`	 BIGINT,
`fw`	 BIGINT,
`fx`	 BIGINT,
`fy`	 BIGINT,
`fz`	 BIGINT,
`gca`	 BIGINT,
`gcb`	 BIGINT,
`gcc`	 BIGINT,
`gcd`	 BIGINT,
`gce`	 BIGINT,
`gcf`	 BIGINT,
`gcg`	 BIGINT,
`gch`	 BIGINT,
`gcj`	 BIGINT,
`gck`	 BIGINT,
`gcl`	 BIGINT,
`gcm`	 BIGINT,
`gcn`	STRING,
`gco`	STRING,
`gcp`	 INT,
`gcq`	 BIGINT,
`gcr`	 BIGINT,
`gcs`	 BIGINT,
`gct`	 BIGINT,
`gcu`	 BIGINT,
`gcv`	 INT,
`gcw`	 INT,
`gcx`	 INT,
`gcy`	 INT,
`gcz`	 INT,
`ger`	 INT,
`get`	 INT,
`gey`	 INT,
`geu`	 INT
) STORED AS PARQUET'''


cur.execute(sql)
```
