### ISSUE TITLE
math trigonometry functions not supported in UDFs?

### ISSUE THREAD

**Issue by DandyDev** [cloudera/impyla#56]
I've managed to successfully ship the `int_promotion` UDF that is somewhere in the tests to Impala, but now I'm trying a more complex function and it does not work. This is the code I use to ship the UDF:

```python
from impala.udf import udf, ship_udf
from impala.udf.types import (FunctionContext, DoubleVal)
from impala.context import ImpalaContext
import math

@udf(DoubleVal(FunctionContext, DoubleVal, DoubleVal, DoubleVal, DoubleVal))
def distance(context, lat1, long1, lat2, long2):

    R = 6378.1 # KMs

    # Convert latitude and longitude to
    # spherical coordinates in radians.
    degrees_to_radians = math.pi/180.0

    # phi = 90 - latitude
    phi1 = (90.0 - lat1)*degrees_to_radians
    phi2 = (90.0 - lat2)*degrees_to_radians

    # theta = longitude
    theta1 = long1*degrees_to_radians
    theta2 = long2*degrees_to_radians

    # Compute spherical distance from spherical coordinates.

    cos = (math.sin(phi1)*math.sin(phi2)*math.cos(theta1 - theta2) +
           math.cos(phi1)*math.cos(phi2))
    arc = math.acos( cos )

    # Multiply arc by the radius of the earth
    # in your favorite set of units to get length.
    return arc * R

ctx = ImpalaContext(nn_host='ec2-xx-xx-xx-xx.eu-west-1.compute.amazonaws.com', host='ec2-xx-xx-xx-xx.eu-west-1.compute.amazonaws.com', hdfs_user='hdfs', webhdfs_port=50070)

ship_udf(ctx, int_promotion, overwrite=True, hdfs_path='/tmp/impala_functions/distance.ll', database='default')

ctx.close()
```

And this is the output I get:

```
Traceback (most recent call last):
  File "install_distance.py", line 6, in <module>
    @udf(DoubleVal(FunctionContext, DoubleVal, DoubleVal, DoubleVal, DoubleVal))
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/impala/udf/__init__.py", line 34, in wrapper
    udfobj = UDF(pyfunc, signature)
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/impala/udf/__init__.py", line 57, in __init__
    flags=flags, locals={})
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/numba/compiler.py", line 261, in compile_extra
    return self.compile_bytecode(res.result, func_attr=self.func_attr)
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/numba/compiler.py", line 275, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/numba/compiler.py", line 501, in _compile_bytecode
    return self._run_pipeline(pipelines)
  File "/Users/daan/.virtualenvs/hermes/lib/python2.7/site-packages/numba/compiler.py", line 526, in _run_pipeline
    raise _raise_error(msg, res.exception)
numba.lowering.LoweringError: Failed at nopython mode backend
Internal error:
Exception: No definition for lowering <built-in function sin>(float64,) -> float64
File "install_distance.py", line 31
```

I assume this is a Numba problem, but I can't find any documentation on python `math` support in Numba. Has anyone else experienced this issue? Or am I just doing something wrong? :)

**Comment by DandyDev** [comment]
Update: using the trigonometry from NumPy, yields the same results.

**Comment by DandyDev** [comment]
@laserson do you have any idea what might be going wrong here? :)

**Comment by cgc17** [comment]
@DandyDev I am having similar issues with `math.log10()`.  Were you ever able to get `math` functions working with UDFs?

**Comment by DandyDev** [comment]
Sadly, no. In the end, I applied my severely lacking C++ skills to create the UDF in C++ :)
@laserson any idea how to fix this?

**Comment by laserson** [comment]
This is surprising to me, but definitely must be the case that numba doesn't know how to plug in the numpy/math fns.  Either way, this functionality is now stuck at an old version of numba bc they switched to llvmlite which broke their internal API, and requires non-trivial changes to the impyla UDF code.  However, we're deprecating all this functionality in impyla since it will be re-explored in ibis, which you should check out if you haven't seen: ibis-project.org.

**Comment by DandyDev** [comment]
I've seen Ibis yeah, looks promising. In the meanwhile I'm getting better at C++, which works so far for me.
