### ISSUE TITLE
Executing statements in multiple processes simultaneously produces an error

### ISSUE THREAD

**Issue by misalmi** [cloudera/impyla#6]
Example case:

from impala.dbapi import connect
from multiprocessing import Process
conn = connect("127.0.0.1", 21050)
cursor = conn.cursor()

def f():
    cursor.execute("SHOW TABLES")
    print cursor.fetchall()

def g():
    Process(target=f).start()

[g() for i in range(10)]

Error:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(_self._args, *_self._kwargs)
  File "<stdin>", line 2, in f
  File "/usr/lib/python2.6/site-packages/impala/dbapi.py", line 156, in execute
    self._execute_sync(op)
  File "/usr/lib/python2.6/site-packages/impala/dbapi.py", line 164, in _execute_sync
    self._wait_to_finish()  # make execute synchronous
  File "/usr/lib/python2.6/site-packages/impala/dbapi.py", line 185, in _wait_to_finish
    self._last_operation_handle)
  File "/usr/lib/python2.6/site-packages/impala/rpc.py", line 118, in wrapper
    return func(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/impala/rpc.py", line 329, in get_operation_status
    return TOperationState._VALUES_TO_NAMES[resp.operationState]
KeyError: None

This doesn't happen if conn.cursor() is called in f to get a new cursor on each iteration. However, I do not think this is an error, which is supposed to be produced in this scenario.

**Comment by IamGianluca** [comment]
Hi, sorry for resuming this old thread. I'm working on an application that should read from a Hive database frequently. The application is designed to be always available, 24/7. In this context, is it okay to instantiate a `Connection`, and then open and close a `Cursor` object every time I need to execute a query against the database? Before executing any query against the database I would of course check the connection is still up and running, and only if it is not, I would open a new one with the same details.
