### ISSUE TITLE
HS2Error when running as_pandas

### ISSUE THREAD

**Issue by jvns** [cloudera/impyla#7]
I'm running a smallish query (the result is 8MB of data), and getting an `HS2Error` when I try to read the data. `as_pandas` is working on smaller queries. Any idea what could be going on here?

Here's what I'm running:

```
import impala.dbapi
from impala.util import as_pandas
c = impala.dbapi.connect(port=21050).cursor() # works fine
c.execute("[my query]") # works fine
df = as_pandas(c) # oh no!
```

and the error:

```
---------------------------------------------------------------------------
HS2Error                                  Traceback (most recent call last)
<ipython-input-5-bee92ca13acd> in <module>()
----> 1 df = as_pandas(c)

/Users/jocelyn/anaconda/lib/python2.7/site-packages/impyla-0.9.0_dev-py2.7.egg/impala/util.pyc
in as_pandas(cursor)
     21     def as_pandas(cursor):
     22         names = [metadata[0] for metadata in cursor.description]
---> 23         return pd.DataFrame([dict(zip(names, row)) for row in
cursor], columns=names)
     24 except ImportError:
     25     print "Failed to import pandas"

/Users/jocelyn/anaconda/lib/python2.7/site-packages/impyla-0.9.0_dev-py2.7.egg/impala/dbapi.pyc
in next(self)
    246             rows = impala.rpc.fetch_results(self.service,
    247                     self._last_operation_handle, self.description,
--> 248                     self.buffersize)
    249             self._buffer.extend(rows)
    250             if len(self._buffer) == 0:

/Users/jocelyn/anaconda/lib/python2.7/site-packages/impyla-0.9.0_dev-py2.7.egg/impala/rpc.pyc
in wrapper(*args, **kwargs)
    116                 if not transport.isOpen():
    117                     transport.open()
--> 118                 return func(*args, **kwargs)
    119             except socket.error as e:
    120                 pass

/Users/jocelyn/anaconda/lib/python2.7/site-packages/impyla-0.9.0_dev-py2.7.egg/impala/rpc.pyc
in fetch_results(service, operation_handle, schema, max_rows,
orientation)
    235                            maxRows=max_rows)
    236     resp = service.FetchResults(req)
--> 237     err_if_rpc_not_ok(resp)
    238
    239     rows = []

/Users/jocelyn/anaconda/lib/python2.7/site-packages/impyla-0.9.0_dev-py2.7.egg/impala/error.pyc
in err_if_rpc_not_ok(resp)
     55     if (resp.status.statusCode !=
TStatusCode._NAMES_TO_VALUES['SUCCESS_STATUS'] and
     56             resp.status.statusCode !=
TStatusCode._NAMES_TO_VALUES['SUCCESS_WITH_INFO_STATUS']):
---> 57         raise HS2Error(resp.status.errorMessage)

HS2Error: Invalid session id
```

**Comment by schaffino** [comment]
I've managed to encounter the same issue. The following code works consistently if i use pyodbc instead of impyla. With impyla it fails intermittently. The table I am invalidating and retrieving stats on is about 4TB has about 700 partitions and is about 500 columns wide.

```python
from impala.dbapi import connect
conn = connect(host="server",port=21050,use_kerberos=True,database="database")
conn = pyodbc.connect(DSN='impala-bda', autocommit=True)
cursor_impala = conn.cursor()
cursor_impala.execute('invalidate metadata table1')
cursor_impala.execute('show table stats table1')
results1=cursor_impala.fetchall()
```

The stack trace

```python
Traceback (most recent call last):
  File "./testimpyla2.py", line 8, in <module>
    cursor_impala.execute('show table stats raw_clickstream')
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/dbapi/hiveserver2.py", line 152, in execute
    self._execute_sync(op)
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/dbapi/hiveserver2.py", line 158, in _execute_sync
    operation_fn()
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/dbapi/hiveserver2.py", line 150, in op
    configuration)
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/_rpc/hiveserver2.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/_rpc/hiveserver2.py", line 233, in execute_statement
    err_if_rpc_not_ok(resp)
  File "/dhcommon/dhpython/python/lib/python2.7/site-packages/impala/_rpc/hiveserver2.py", line 80, in err_if_rpc_not_ok
    raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: Invalid session id
```

**Comment by mariusvniekerk** [comment]
Sounds like a timeout.  You may want to increase your Connection's timeout. 

After invalidating a table it can take quite a lot of hive metastore calls before it becomes operational again.

**Comment by schaffino** [comment]
Thanks Marius, that's fixed it for me. Not a particularly helpful error message from Hive server 2 in this instance.

**Comment by laserson** [comment]
Also see #128

**Comment by wilberh** [comment]
Adding a timeout to the connection didn't help.  I had to switch to pyhive.  :/
